// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TrackDeletesAndUndeletes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TrackDeletesAndUndeletes));
        
        string IMigrationMetadata.Id
        {
            get { return "201604020746519_TrackDeletesAndUndeletes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
